name: Update README

on:
  schedule:
    - cron: '*/120 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: BatemaDevelopment/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: 'Lukas-Batema'
        with:
          TARGET_FILE: /profile/README.md
